apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels: {{- include "mylabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- include "serviceport" . | nindent 4 }}
  selector:
    app: nginx
